# Step 1: Build the Next.js application
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Step 2: Create the production image
FROM node:22-alpine AS runner
WORKDIR /app
# These files are generated by 'npm run build' and must be copied
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static

ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000
CMD ["node", "server.js"]